apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: project-management
data:
  NODE_ENV: "production"
  PORT: "3000"
  API_PREFIX: "api/v1"
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "project_management"
  DB_SYNC: "false"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  THROTTLE_TTL: "60"
  THROTTLE_LIMIT: "100"
